name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    env:
      HUGO_VERSION: 0.137.1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
    timeout-minutes: 3
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: hugo node-version
        run: hugo version

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Sync public folder to S3
        run: |
          # Excludes the specific wasm file from being deleted during the sync
          aws s3 sync public/ s3://bappa-docs/ --delete --exclude "wasmbin/templates/concrete_echos.wasm"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
